# TCL File Generated by Component Editor 18.1
# Mon Nov 09 15:47:17 CET 2020
# DO NOT MODIFY


# 
# 7_Segment "7_Segment" v1.0
#  2020.11.09.15:47:17
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module 7_Segment
# 
set_module_property DESCRIPTION ""
set_module_property NAME 7_Segment
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME 7_Segment
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Segment_7
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file 7_Segment_Decoder.vhd VHDL PATH ../hdl/7_Segment_Decoder.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


# 
# connection point conduit_SelSeg
# 
add_interface conduit_SelSeg conduit end
set_interface_property conduit_SelSeg associatedClock clock
set_interface_property conduit_SelSeg associatedReset reset_sink
set_interface_property conduit_SelSeg ENABLED true
set_interface_property conduit_SelSeg EXPORT_OF ""
set_interface_property conduit_SelSeg PORT_NAME_MAP ""
set_interface_property conduit_SelSeg CMSIS_SVD_VARIABLES ""
set_interface_property conduit_SelSeg SVD_ADDRESS_GROUP ""

add_interface_port conduit_SelSeg SelSeg export Output 8


# 
# connection point conduit_LedButton
# 
add_interface conduit_LedButton conduit end
set_interface_property conduit_LedButton associatedClock clock
set_interface_property conduit_LedButton associatedReset reset_sink
set_interface_property conduit_LedButton ENABLED true
set_interface_property conduit_LedButton EXPORT_OF ""
set_interface_property conduit_LedButton PORT_NAME_MAP ""
set_interface_property conduit_LedButton CMSIS_SVD_VARIABLES ""
set_interface_property conduit_LedButton SVD_ADDRESS_GROUP ""

add_interface_port conduit_LedButton LedButton export Output 4


# 
# connection point conduit_nSelDig
# 
add_interface conduit_nSelDig conduit end
set_interface_property conduit_nSelDig associatedClock clock
set_interface_property conduit_nSelDig associatedReset reset_sink
set_interface_property conduit_nSelDig ENABLED true
set_interface_property conduit_nSelDig EXPORT_OF ""
set_interface_property conduit_nSelDig PORT_NAME_MAP ""
set_interface_property conduit_nSelDig CMSIS_SVD_VARIABLES ""
set_interface_property conduit_nSelDig SVD_ADDRESS_GROUP ""

add_interface_port conduit_nSelDig nSelDig export Output 6


# 
# connection point conduit_nButton
# 
add_interface conduit_nButton conduit end
set_interface_property conduit_nButton associatedClock clock
set_interface_property conduit_nButton associatedReset reset_sink
set_interface_property conduit_nButton ENABLED true
set_interface_property conduit_nButton EXPORT_OF ""
set_interface_property conduit_nButton PORT_NAME_MAP ""
set_interface_property conduit_nButton CMSIS_SVD_VARIABLES ""
set_interface_property conduit_nButton SVD_ADDRESS_GROUP ""

add_interface_port conduit_nButton nButton export Input 4


# 
# connection point conduit_Reset_Led
# 
add_interface conduit_Reset_Led conduit end
set_interface_property conduit_Reset_Led associatedClock clock
set_interface_property conduit_Reset_Led associatedReset reset_sink
set_interface_property conduit_Reset_Led ENABLED true
set_interface_property conduit_Reset_Led EXPORT_OF ""
set_interface_property conduit_Reset_Led PORT_NAME_MAP ""
set_interface_property conduit_Reset_Led CMSIS_SVD_VARIABLES ""
set_interface_property conduit_Reset_Led SVD_ADDRESS_GROUP ""

add_interface_port conduit_Reset_Led Reset_Led export Output 1

